---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# MQmetrics

<!-- badges: start -->
<!-- badges: end -->

The goal of MQmetrics is to analyze Proteomics data from LC-MS/MS. It takes the output tables from MaxQuant and plots multiple parameters.

## Installation

<!-- You can install thess released version of MQmetrics from [CRAN](https://CRAN.R-project.org) with: -->

<!-- ``` r -->
<!-- install.packages("MQmetrics") -->
<!-- ``` -->

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("BioAlvaro/MQmetrics")
```
## Example

```{r setup}
library(MQmetrics)
```

```{r, message=FALSE, warning=FALSE}
MQPathCombined <- '/home/alvaro/Documents/MaxQuant/example2/'

files <- ReadDataFromDir(MQPathCombined) #This function will read the tables needed for creating the outputs.

# files can be extracted like this:

summary <- files[["summary.txt"]]
evidence <- files[["evidence.txt"]]
msScans <- files[['msScans.txt']]
peptides <- files[["peptides.txt"]]
msmsScans <- files[["msmsScans.txt"]]
proteinGroups <- files[["proteinGroups.txt"]]
modificationSpecificPeptides <- files[["modificationSpecificPeptides.txt"]]
parameters <- files[["parameters.txt"]]
runningTimes <-  files[["#runningTimes.txt"]]
```

```{r ExperimentDuration, comment= NA}
ExperimentInformation(runningTimes, parameters) 
```

```{r PlotProteins}
PlotProteinsIdentified(proteinGroups, intensity_type = 'Intensity', long_names = TRUE, sep_names = '_')
```

```{r PeptidesIdentified, warning=FALSE , fig.height=5, fig.width=7.2}
PlotPeptidesIdentified(summary, long_names = TRUE, sep_names = '_')
```

```{r PlotMSMS, fig.height=5, fig.width=7.2}
PlotMsMs(summary,long_names = TRUE, sep_names = '_')
```

```{r PlotPeaks, fig.height=5, fig.width=7.2}
PlotPeaks(summary, long_names = TRUE, sep_names = '_')
```

```{r isotope, fig.height=5, fig.width=7.2}
PlotIsotopePattern(summary,long_names = TRUE, sep_names = '_')
```

```{r Charg, warning=FALSE, message=FALSE, fig.height=6, fig.width=7.2}
PlotCharge(evidence)
```

```{r missed_cleavages,fig.height=10}
PlotProteaseSpecificity(peptides)
```

```{r PlotHydrophobicity, warning= FALSE, message= FALSE}
PlotHydrophobicity(peptides, palette = 'Set2', show_median =  TRUE, binwidth = 0.1)
```

```{r AndromedaScore, message = FALSE, warning = FALSE}
PlotAndromedaScore(peptides)
```

```{r IdentificationType,message = FALSE, warning = FALSE, fig.height=5, fig.width=7.2}
if(parameters$Value[27] == "True"){
  PlotIdentificationType(peptides, 
                         proteinGroups,
                         palette = 'Set2',
                         long_names = TRUE, 
                         sep_names = '_')  
} else{
  cat('Match Between Runs was not used during the MaxQuant analysis.
No Identification Type to show.')
}
```

```{r PlotIntensity, warning = FALSE, fig.height=5, fig.width=7.2}
PlotIntensity(proteinGroups, split_violin_intensity = TRUE, intensity_type = 'LFQ', 
              log_base = 2, long_names = TRUE, sep_names = '_')
```

```{r PlotPCA, warning = FALSE, fig.height=5, fig.width=7.2}
PlotPCA(proteinGroups, intensity_type = 'Intensity', palette = 'Set2')
```

```{r DynamicRange, fig.height=5, fig.width=7.2}
PlotCombinedDynamicRange(proteinGroups, show_shade = TRUE, percent_proteins = 0.79)
```

```{r DynamicRangeAll, fig.height=10, fig.width=7.2}
PlotAllDynamicRange(proteinGroups,show_shade = TRUE, percent_proteins = 0.90)
```

```{r protein_coverage_all}
PlotProteinCoverageAll(proteinGroups)

```

```{r protein_degradation}
PlotProteinCoverage(peptides,proteinGroups, UniprotID = "Q8R0Y6", log_base = 10, segment_width = 1)
```

```{r irt_peps1, warning = FALSE, message= FALSE, fig.height=8, fig.width=9.2}
PlotiRT(evidence)
```

```{r irt_peps2, warning = FALSE, message= FALSE, fig.height=8, fig.width=9.2}
PlotiRTScore(evidence)
```

```{r TotalIonCurrent, fig.height=10, fig.width=7.2}
PlotTotalIonCurrent(msmsScans, show_max_value = TRUE)
```

```{r PlotAcquisition, fig.height= 10, warning=FALSE, message=FALSE}
PlotAcquisitionCycle(msScans)
```

```{r PTM, fig.height=8, fig.width=7.2}
PlotPTM(modificationSpecificPeptides, peptides_modified = 3)
```


