---
title: "ProteoMS"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ProteoMS}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ProteoMS)
```

```{r, message=FALSE, warning=FALSE}
MQPathCombined <- system.file('extdata', package = 'ProteoMS') #is the directory with the output of the MaxQuant analysis.

#MQPathCombined <- '/home/alvaro/Documents/MaxQuant_results/combined/'

files <- ReadDataFromDir(MQPathCombined) #This function will read the tables needed for creating the outputs.

#files can be extracted like this:
summary <- files[["summary.txt"]]
evidence <- files[["evidence.txt"]]
peptides <- files[["peptides.txt"]]
msmsScans <- files[["msmsScans.txt"]]  
proteinGroups <- files[["proteinGroups.txt"]]
runningTimes <-  files[["#runningTimes.txt"]]
parameters <- files[["parameters.txt"]]
```


```{r ExperimentDuration}
ExperimentInformation(runningTimes, parameters) 
```



```{r PlotPeaks, fig.height=5, fig.width=7.2}
PlotPeaks(summary)
```


```{r PlotMSMS, fig.height=5, fig.width=7.2}
PlotMsMs(summary)
```


```{r isotope, fig.height=5, fig.width=7.2}
PlotIsotopePattern(summary)
```


```{r PeptidesIdentified, warning=FALSE , fig.height=5, fig.width=7.2}
PLotPeptidesIdentified(summary)
```

```{r PlotIntensity, warning = FALSE, fig.height=5, fig.width=7.2}

PlotIntensity(proteinGroups, intensity_type = 'LFQ')

```

```{r MissedCleavages, warning = FALSE, fig.height=5, fig.width=7.2}
PlotMissedCleavages(peptides)
```

```{r IdentificationType, warning = FALSE, fig.height=5, fig.width=7.2}
PlotIdentificationType(peptides)
```


```{r Charg, warning=FALSE, message=FALSE, fig.height=5, fig.width=7.2}
PlotCharge(evidence)
```

```{r TotalIonCurrent, fig.height=5, fig.width=7.2}
PlotTotalIonCurrent(msmsScans)
```

```{r DynamicRange, fig.height=5, fig.width=7.2}
PlotCombinedDynamicRange(proteinGroups)
```

```{r DynamicRangeAll, fig.height=8, fig.width=7.2}
PLotAllDynamicRange(proteinGroups,columns = 1,rows = 3)
```

